<?php

/**
 * @file
 * Contains recipe_share_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function recipe_share_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the recipe_share_core module.
    case 'help.page.recipe_share_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
